# Generated by Django 3.0.1 on 2020-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.IntegerField()),
                ('cl_fname', models.CharField(max_length=10)),
                ('cl_lname', models.CharField(max_length=10)),
                ('cl_phone', models.IntegerField(max_length=20)),
                ('cl_email', models.EmailField(max_length=254)),
                ('cl_password', models.CharField(max_length=200)),
                ('cl_age', models.IntegerField()),
                ('cl_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cl_photo', models.ImageField(blank=True, upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField()),
                ('db_fname', models.CharField(max_length=10)),
                ('db_lname', models.CharField(max_length=10)),
                ('db_phone', models.IntegerField()),
                ('db_email', models.EmailField(max_length=254)),
                ('db_password', models.CharField(max_length=100)),
                ('db_age', models.IntegerField()),
                ('db_photo', models.ImageField(blank=True, upload_to='delivery')),
                ('db_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
