# Generated by Django 3.0.1 on 2020-01-03 10:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicStores', '0002_auto_20200103_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.IntegerField()),
                ('cl_fname', models.CharField(max_length=10)),
                ('cl_lname', models.CharField(max_length=10)),
                ('cl_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('cl_email', models.EmailField(max_length=254)),
                ('cl_password', models.CharField(max_length=200)),
                ('cl_age', models.IntegerField()),
                ('cl_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cl_photo', models.ImageField(blank=True, upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField()),
                ('db_fname', models.CharField(max_length=10)),
                ('db_lname', models.CharField(max_length=10)),
                ('db_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('db_email', models.EmailField(max_length=254)),
                ('db_password', models.CharField(max_length=100)),
                ('db_age', models.IntegerField()),
                ('db_photo', models.ImageField(blank=True, upload_to='delivery')),
                ('db_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
