# Generated by Django 3.0.1 on 2020-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicStores', '0003_auto_20200103_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_photo',
            field=models.ImageField(blank=True, upload_to='media/client'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='db_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='db_photo',
            field=models.ImageField(blank=True, upload_to='media/delivery'),
        ),
    ]
