# Generated by Django 3.0.1 on 2020-01-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicStores', '0005_auto_20200107_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='cl_id',
        ),
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='o_id',
        ),
        migrations.DeleteModel(
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cl_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='db_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='cl_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sc_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='c_id',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='deliveryboy',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
        migrations.DeleteModel(
            name='prescription',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='status',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
