# Generated by Django 3.0.1 on 2020-01-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicStores', '0007_auto_20200109_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='deliveryboymodel',
            name='DOB',
        ),
    ]
